env:
  INPUT_TYPE: bytes
  INDEX_YAML: yamls/index.yml
  QUERY_YAML: yamls/query.yml
  NUM_DOCS: 
    - 512
    - 1024
  BATCH_SIZE: 256
  EMBED_DIM: 16
  FILE_DIR: .data
  NUM_BYTES_PER_DOC: 10
  NUM_CHUNKS_PER_DOC: 5
  NUM_SENTENCES_PER_DOC: 10
