jtype: ImageTorchEncoder
with:
  pool_strategy: mean
  model_name: mobilenet_v2
  img_shape: 96
  channel_axis: -1
requests:
  on:
    ControlRequest:
      - jtype: ControlReqDriver {}
    [IndexRequest, SearchRequest]:
      - jtype: EncodeDriver
        with:
          traversal_paths: ['r']
          batch_size: {{ JINA_ENCODER_DRIVER_BATCHING }}
