jobs:
  images-stress-test:
    steps:
      - method: create_workspace
        environment:
          JINA_GATEWAY_REST: false
          JINA_GATEWAY_PORT_EXPOSE: 23456
          JINA_ENCODER_SHARDS: 12
          JINA_VEC_INDEXER_SHARDS: 12
          JINA_KV_INDEXER_SHARDS: 12
          JINA_SCHEDULING: load_balance
          JINA_ENCODER_DRIVER_BATCHING: 16
          JINA_WORKSPACE: workspace
          JINA_DISTANCE_REVERSE: false
        files:
          - images/encoder.yml
          - images/vec.yml
          - images/binarypb.yml
          - images/merge_and_topk.yml
          - images/annoy_indexer.yml
          - images/faiss_indexer.yml
          - images/remote/index_numpy_binarypb.yml
          - images/remote/query_numpy_binarypb.yml
          - images/remote/query_annoy_binarypb.yml
          - images/remote/query_faiss_binarypb.yml

      # Index using numpy + binarypb
      - method: start_flow
        file: images/remote/index_numpy_binarypb.yml
      - sleep_time: 20
        method: index
        execution_time: 480
        inputs:
          method: random_images
          kwargs:
            num_docs: 200
        on_always:
          method: validate_images
          kwargs:
            type: 'Numpy+BinaryPb+ImageTorch'
        client: grpc
        num_clients: 15
        request_size: 100
      - method: terminate_flow

      # Query using numpy + binarypb
      - method: start_flow
        file: images/remote/query_numpy_binarypb.yml
      - sleep_time: 30
        method: query
        execution_time: 240
        inputs:
          method: random_images
          kwargs:
            num_docs: 50
        on_always:
          method: validate_images
          kwargs:
            type: 'Numpy+BinaryPb+ImageTorch'
        client: grpc
        num_clients: 15
        request_size: 100
        top_k: 15
      - method: terminate_flow

      # Query using annoy + binarypb
      - method: update_workspace
        environment:
          JINA_ANNOY_NUM_TREES: 100
          JINA_ANNOY_SEARCH_K: -1
          JINA_ANNOY_IMAGE: 'docker://jinahub/pod.indexer.annoyindexer:0.0.18-1.2.0'
          OMP_NUM_THREADS: 1
          JINA_GATEWAY_REST: false
          JINA_GATEWAY_PORT_EXPOSE: 23456
        files:
          - images/annoy_indexer.yml
          - images/remote/query_annoy_binarypb.yml
      - method: start_flow
        file: images/remote/query_annoy_binarypb.yml
      - sleep_time: 1
        method: query
        execution_time: 240
        inputs:
          method: random_images
          kwargs:
            num_docs: 50
        on_always:
          method: validate_images
          kwargs:
            type: 'Annoy+BinaryPb+ImageTorch'
        client: grpc
        num_clients: 10
        request_size: 100
        top_k: 15
      - method: terminate_flow

      # Query using faiss + binarypb
      - method: update_workspace
        environment:
          JINA_FAISS_INDEX_KEY: 'IVF50,Flat'
          JINA_FAISS_IMAGE: 'docker://jinahub/pod.indexer.faissindexer:0.0.19-1.2.0'
          JINA_GATEWAY_REST: false
          JINA_GATEWAY_PORT_EXPOSE: 23456
        files:
          - images/faiss_indexer.yml
          - images/remote/query_faiss_binarypb.yml
      - method: start_flow
        file: images/remote/query_faiss_binarypb.yml
      - sleep_time: 1
        method: query
        execution_time: 240
        inputs:
          method: random_images
          kwargs:
            num_docs: 50
        on_always:
          method: validate_images
          kwargs:
            type: 'Faiss+BinaryPb+ImageTorch'
        client: grpc
        num_clients: 15
        request_size: 100
        top_k: 15
      - method: terminate_flow

      - method: delete_workspace

      - method: collect_stats
        slack: true

      - method: upload_to_s3
        directory: '_logs'
        bucket: 'e2e-distributed-stress-tests'
