jobs:
  images-stress-test:
    steps:
      - method: create_workspace
        environment:
          JINA_GATEWAY_REST: false
          JINA_GATEWAY_PORT_EXPOSE: 23456
          JINA_ENCODER_SHARDS: 2
          JINA_VEC_INDEXER_SHARDS: 2
          JINA_KV_INDEXER_SHARDS: 1
          JINA_SCHEDULING: load_balance
          JINA_ENCODER_DRIVER_BATCHING: 16
          JINA_WORKSPACE: workspace
          JINA_DISTANCE_REVERSE: false
        files:
          - images/encoder.yml
          - images/vec.yml
          - images/binarypb.yml
          - images/merge_and_topk.yml
          - images/index_local.yml
          - images/query_local.yml

      - method: start_flow
        file: images/index_local.yml
      - sleep_time: 2
        method: index
        execution_time: 10
        inputs:
          method: random_images
          kwargs:
            num_docs: 50
        on_always:
          method: validate_images
          kwargs:
            top_k: 2
        client: grpc
        num_clients: 1
        request_size: 5
      - method: terminate_flow

      - method: update_workspace
        environment:
          JINA_GATEWAY_REST: true
          JINA_GATEWAY_PORT_EXPOSE: 23456
        files:
          - images/index_local.yml

      - method: start_flow
        file: images/index_local.yml
      - sleep_time: 2
        method: index
        execution_time: 10
        inputs:
          method: random_images
          kwargs:
            num_docs: 50
        on_always:
          method: validate_images
          kwargs:
            top_k: 2
        client: websocket
        num_clients: 1
        request_size: 5
      - method: terminate_flow

      - method: update_workspace
        environment:
          JINA_GATEWAY_REST: false
          JINA_GATEWAY_PORT_EXPOSE: 23456
        files:
          - images/query_local.yml
      - method: start_flow
        file: images/query_local.yml
      - sleep_time: 1
        method: query
        execution_time: 10
        inputs:
          method: random_images
          kwargs:
            num_docs: 10
        on_always:
          method: validate_images
        client: grpc
        num_clients: 1
        request_size: 5
        top_k: 15
      - method: terminate_flow

      - method: update_workspace
        environment:
          JINA_GATEWAY_REST: true
          JINA_GATEWAY_PORT_EXPOSE: 23456
        files:
          - images/query_local.yml
      - method: start_flow
        file: images/query_local.yml
      - sleep_time: 1
        method: query
        execution_time: 10
        inputs:
          method: random_images
          kwargs:
            num_docs: 10
        on_always:
          method: validate_images
        client: websocket
        num_clients: 1
        request_size: 5
        top_k: 15
      - method: terminate_flow

      - method: delete_workspace

      - method: upload_to_s3
        directory: '_logs'
        bucket: 'e2e-distributed-stress-tests'
